### ISSUE TITLE
Compilation on Mac OS

### ISSUE THREAD

**Issue by MFaisalZaki** [santiontanon/SHRDLU#2]
Hello, 

At the beginning, I want to congratulate you on this achievement which is a mind blowing btw.
I was wondering if you can provide building instructions to build SHRDLU on mac.

Also can it be ported to C# or C++?  I can help with this porting if possible.

Best regards.

**Comment by santiontanon** [comment]
Thank you!! And absolutely, happy to provide the build script! I should have included it in the repo. I just added it. Just open a terminal, go to SHRDLU's folder and type "./build"

Compilation requires having the Typescript compiler (tsc) in the path. I use tsc version 2.9.2, but I assume later versions should work too!

The result of compilation will be a "built" folder that contains the game ready to be put on a web server and played (basically, it should be identical than the "demo" version linked on the read me file at this point). Let me know if this works for you!

As for porting, that's not currently on my plans. But maybe after the game is finished, porting it would be nice :)

**Comment by MFaisalZaki** [comment]
Great, I think we can start porting a least the generic part related to the AI system If you can provide any guide to implement it this will be great, then you finish the game it will be much easier to port it.

Best regards.

**Comment by santiontanon** [comment]
Sure thing, there are a collection of classes on the AI side that are independent of the game, and can be compiled separately (I do this all the time for testing). In particular, you can just compile the following files:

src/ai/*.ts 
src/ai/nlp/*.ts 
src/ai/tests/*.ts 
src/auxiliar/auxiliar.ts 
src/ai/inferences/InferenceExecuteAction.ts 
src/ai/inferences/InferenceStopAction.ts

If you do that, you can already run all the test cases inside of src/ai/tests, which is what I use to test the NLP and inference part of the AI. This is independent of the game engine, and could be reused in other games with different game engines.

**Comment by santiontanon** [comment]
I am going to close this issue, feel free to reopen if you have further questions :)
